# Description:  Creates a Virtual Private Cloud with the name openebs-e2e, that will be specified
# with all other clusters. Using --subnet-mode=auto will create a subnet for every zone. This file
# is ran at the beginning of e2e tests
# Author: Harshvardhan Karn
###############################################################################################
#Steps:
#1. Create a VPC, openebs-e2e in Google Cloud
###############################################################################################

---
- hosts: localhost
  vars_files:
    - gcp-vars.yml
  tasks:
       - block:
             - name: Creating VPC `openebs-e2e`
               shell: gcloud compute --project=openebs-ci networks create openebs-e2e --subnet-mode=auto > ~/e2e/GCP/cases/{{ create_vpc_case_id }}/logs
             - name: Test Passed
               set_fact:
                 flag: "Test Passed"
                 status_id: 1
         rescue:
             - name: Test Failed
               set_fact:
                 flag: "Test Failed"
                 status_id: 5

       - lineinfile:
           create: yes
           state: present
           path: '~/e2e/GCP/cases/{{ create_vpc_case_id }}/result.json'
           line: '{ "name" : "create-vpc", "case_id" : {{ create_vpc_case_id | to_json }}, "suite_id" : {{ gcp_test_suite_id | to_json }}, "status" : {{ flag | to_json }}, "status_id" : {{ status_id | to_json }} }'