# Description:  Deletes the Cluster and the Bucket associated the NAME passed as the extra-var
# in playbook, e.g. --extra-vars="NAME=<cluster-name>" 
# Author: Harshvardhan Karn
###############################################################################################
# Steps:
# 1. Delete the Cluster
# 2. Delete the Bucket
###############################################################################################
---
- hosts: localhost
  vars_files:
    - gcp-vars.yml
  tasks:
       - block:
             - name: Fetching Cluster Name
               shell: cat ~/e2e/GCP/cases/{{ create_cluster_case_id }}/clusters
               register: cluster_name

             - name: Deleting Cluster
               shell: kops delete cluster --yes --name {{ cluster_name.stdout }}.k8s.local --state gs://{{ cluster_name.stdout }}/ >> ~/e2e/GCP/cases/{{ delete_cluster_case_id }}/logs
             
             - name: Deleting Bucket
               shell: gsutil rm -r gs://{{ cluster_name.stdout }}/ >> ~/e2e/GCP/cases/{{ delete_cluster_case_id }}/logs

             - name: Deleting SSD/Disks
               shell: gcloud compute disks delete a-etcd-events-{{ cluster_name.stdout }}-k8s-local --zone=us-central1-a -q || gcloud compute disks delete a-etcd-main-{{ cluster_name.stdout }}-k8s-local --zone=us-central1-a -q

             - name: Removing Cluster Name Log
               shell: rm ~/e2e/GCP/cases/{{ create_cluster_case_id }}/clusters
             - name: Test Passed
               set_fact:
                 flag: "Test Passed"
                 status_id: 1
         rescue:
             - name: Test Failed
               set_fact:
                 flag: "Test Failed"
                 status_id: 5

       - debug:
           msg: '{{ flag }}'
       - lineinfile:
           create: yes
           state: present
           path: '~/e2e/GCP/cases/{{ delete_cluster_case_id }}/result.json'
           line: '{ "name" : "delete-vpc", "case_id" : {{ delete_cluster_case_id | to_json }}, "suite_id" : {{ gcp_test_suite_id | to_json }}, "status" : {{ flag | to_json }}, "status_id" : {{ status_id | to_json }} }'